"""Initial Migration

Revision ID: 821487655b66
Revises: fa2cb8a288c0
Create Date: 2020-07-15 11:41:32.271843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '821487655b66'
down_revision = 'fa2cb8a288c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('passw_secure', sa.String(length=255), nullable=True))
    op.drop_column('users', 'pwd')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pwd', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('users', 'passw_secure')
    # ### end Alembic commands ###
