"""Initial Migration

Revision ID: fa2cb8a288c0
Revises: 67dfad97eb56
Create Date: 2020-07-15 10:52:05.960589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa2cb8a288c0'
down_revision = '67dfad97eb56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('submission_date', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('pwd', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'pwd')
    op.drop_column('comments', 'submission_date')
    # ### end Alembic commands ###
